### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by dieser-niko** [leandertolksdorf/1001-tracklists-api#2]
Currently I'm trying to create my own program to extract all songs from up to 350 videos. Each video has around 10 spotify links I wanted to fetch. Now I've come to the point where 1001tracklists blocked the IP at my workplace and I can't even unblock it.

Is there a known rate limit or at least how fast can you go? Because doing a request every second would take ages.

**Comment by leandertolksdorf** [comment]
Try opening https://www.1001tracklists.com/ manually in your browser and solving the captcha.

**Comment by dieser-niko** [comment]
Already did that 10 times on different devices

**Comment by dieser-niko** [comment]
Update:
The IP got unblocked, even though I've didn't try to solve the captcha lately.
My assumption would be that a staff of 1001tracklists has to approve an unblocking request.
Did you get unblocked instantly after the captcha? Just wanting to make sure

**Comment by dieser-niko** [comment]
Update:
The rate limit is at 100 per <?> minute. That means after 100 requests you get blocked if there are too much requests. The current limit I've tested is 100/4 min or an interval of 2400 ms. Gonna close it for now
