### ISSUE TITLE
Get track start time (cue)

### ISSUE THREAD

**Issue by dashezup** [leandertolksdorf/1001-tracklists-api#3]
[This one](https://www.1001tracklists.com/tracklist/2srxwlwk/miss-melera-colourizon-101-february-2021-02-17.html) for example, the second track starts from 5:55, it's a very important info for a track list.

btw could it get the name of the set for now? It's `Miss Melera - Colourizon 101 February 2021-02-17` for this one.

**Comment by leandertolksdorf** [comment]
Sounds like an interesting feature. I'll get back to this when I have time.
The name of the set is accessable via the "title" attribute.

**Comment by baronet2** [comment]
@dashezup The pull request above (#5) should have what you're looking for.

**Comment by dashezup** [comment]
```
for num, cue, track in zip(tracklist.track_nums, tracklist.cues, tracklist.tracks):
    print(f"{num}. {cue} {track.title}")
```

thanks, just checked it works.
