### ISSUE TITLE
Line 66 - tracklists.py - 1001 changed from leftDiv to left

### ISSUE THREAD

**Issue by randev6** [leandertolksdorf/1001-tracklists-api#7]
1001 appears to have some site updates. The left divider for track info looks to have changed from "leftDiv" to "left"
![leftDiv](https://user-images.githubusercontent.com/78569739/126050157-53f85e92-b92b-45be-a342-2aa68d68c4a6.PNG)

**Comment by bloedboemmel** [comment]
@randev6 changed it in my pull request

**Comment by leandertolksdorf** [comment]
@randev6 Thank you! Just merged :)
