### ISSUE TITLE
Tracklist parsing is broken

### ISSUE THREAD

**Issue by tha23rd** [leandertolksdorf/1001-tracklists-api#9]
Just tested this today with the following url: "https://www.1001tracklists.com/tracklist/1lmf4011"

Am seeing the following:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "\lib\site-packages\tracklists\tracklists.py", line 61, in __init__
    self.fetch()
  File "\lib\site-packages\tracklists\tracklists.py", line 68, in fetch
    self.load_metadata(left_pane)
  File "\lib\site-packages\tracklists\tracklists.py", line 98, in load_metadata
    for interaction_detail in left_pane.find_all("meta", itemprop = "interactionCount"):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by elte0** [comment]
Seems like 1001tracklists updated the website structure again.
I'll try my best fixing this fast but would also be happy about a PR.

**Comment by bloedboemmel** [comment]
@tha23rd Normally the URL ends with ".html" (For example "https://www.1001tracklists.com/tracklist/z2hq2zk/lane-8-spring-2022-mixtape-2022-03-30.html")
I used this api today and it worked just fine, but if I click your url, it doens't exist on the website either.

**Comment by elte0** [comment]
Thanks @bloedboemmel. I'll close this for now.

**Comment by droussis** [comment]
Getting the same error as @tha23rd even when using link with .html:

> url = "https://www.1001tracklists.com/tracklist/z2hq2zk/lane-8-spring-2022-mixtape-2022-03-30.html"
> t1 = Tracklist(url)

**Comment by ofilipelopes** [comment]
> 

Did you fix it?
